# Inventaire Ansible — Liste des serveurs cibles
# ================================================
# Le sujet demande que le déploiement puisse cibler plusieurs serveurs.
# Il suffit d'ajouter des lignes sous [cloud_servers] pour déployer en parallèle.

all:
  children:
    cloud_servers:
      hosts:
        scaleway1:
          ansible_host: 62.210.237.74
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
